services:
  db:
    image: mysql:8.4
    restart: always
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: myapps

volumes:
  db-data:
